Repository BloomCreativeWorks/BloomFramework, pull requests merged in 2018-09, with the labels that each got.

#3 Some optimisations and fixes
  BloomFramework/BloomFramework.vcxproj
  BloomFramework/BloomFramework.vcxproj.filters
  BloomFramework/include/Game.h
  BloomFramework/include/stdIncludes.h
  BloomFramework/packages.config
  BloomFramework/src/Game.cpp
  Test Bench/Test Bench.vcxproj
  Test Bench/Test Bench.vcxproj.filters
  Test Bench/packages.config
Labels: fix

#10 Make textureStore public in Game
  BloomFramework/include/Game.h
  BloomFramework/src/Game.cpp
  Test Bench/main.cpp
Labels: optimization

#9 Add Delta time calculation.
  BloomFramework/BloomFramework.vcxproj
  BloomFramework/BloomFramework.vcxproj.filters
  BloomFramework/include/Game.h
  BloomFramework/include/Timer.h
  BloomFramework/src/Game.cpp
  BloomFramework/src/Timer.cpp
Labels: WIP, enhancement
